### ISSUE TITLE
cannot read Non-ASCII from stdin

### ISSUE THREAD

**Issue by heobo** [wandernauta/yuml#11]
# echo "[中文]-[That]" | ./yuml -s nofunky -o diagram.png
    Traceback (most recent call last):
      File "./yuml", line 184, in <module>
        main()
      File "./yuml", line 181, in main
        request.run()
      File "./yuml", line 111, in run
        data = {'dsl_text':  dsl_text.encode('utf-8')}
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)

**Comment by wandernauta** [comment]
This should be fixed by now. Thanks for the issue report!
