### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by apastel** [wandernauta/yuml#12]
Hello gents. I get the following error when trying to run the program:

```
$ echo "[This]-[That]" | yuml -s nofunky -o diagram.png
Traceback (most recent call last):
  File "/usr/local/bin/yuml", line 190, in <module>
    main()
  File "/usr/local/bin/yuml", line 187, in main
    request.run()
  File "/usr/local/bin/yuml", line 131, in run
    img_name = urlopen(req).read().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte
```

Tried using different output file types. Tried reading from file instead of inline. Just get a corrupted output file. Any suggestions?

I also tried with python 3:

```
$ echo "[This]-[That]" | python3 $(which yuml) -s nofunky -o diagram.png
Traceback (most recent call last):
  File "/usr/local/bin/yuml", line 190, in <module>
    main()
  File "/usr/local/bin/yuml", line 187, in main
    request.run()
  File "/usr/local/bin/yuml", line 131, in run
    img_name = urlopen(req).read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by wandernauta** [comment]
Thanks for reporting this! I can indeed reproduce the problem - odd. I'll give it a look.

**Comment by wandernauta** [comment]
@apastel I've removed the two-step process altogether (it seems like it is no longer necessary) and that seems to fix the problem, at least on my machine. Could you give it another go?

**Comment by apastel** [comment]
Works now. Thanks!

**Comment by wandernauta** [comment]
You're welcome! :shipit: Thanks again for the heads-up.
